---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - centos-7
      - centos-8
      - debian-9
      - debian-10
      - ubuntu-1604
      - ubuntu-1804
      - ubuntu-2004
    puppet:
      - puppet6
      - puppet7
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/spec_helper_acceptance.rb:
  spec_overrides:
    - "proj_root = File.expand_path(File.join(File.dirname(__FILE__), '..'))"
    - "copy_root_module_to(hosts, source: File.join(proj_root, 'tests/site_munge'), module_name: 'site_munge', ignore_list: [])"
