---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el8
      - el9
      - el10
      - debian-11
      - debian-12
      - ubuntu-2204
      - ubuntu-2404
    puppet:
      - puppet8
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/spec_helper_acceptance.rb:
  spec_overrides:
    - "proj_root = File.expand_path(File.join(File.dirname(__FILE__), '..'))"
    - "copy_root_module_to(hosts, source: File.join(proj_root, 'tests/site_munge'), module_name: 'site_munge', ignore_list: [])"
